<a href="https://colab.research.google.com/github/asennakesavan/InceptezGenAI-Batch26/blob/main/Polynominal_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/Laxminarayen/InceptezGenAI-Batch26/refs/heads/main/21.%20Polynomial%20Regression/handson/Salary_Experience_Dataset.csv")

In [3]:
df.head(5)

   years_experience  education_level  certifications  salary_lpa
0              9.38                2               2       22.96
1             13.46                1               2       23.48
2             11.64                0               3       20.78
3              3.38                2               3       14.55
4              4.50                1               1       13.11

In [12]:
scaler = MinMaxScaler()
df['edu_norm'] = scaler.fit_transform(df[['years_experience']])

Lin_model = LinearRegression() # Instantiate the model
Lin_model.fit(df[['years_experience']], df['salary_lpa']) # Pass X as a DataFrame and y as a Series
print(f"   Salary = {Lin_model.intercept_:,.0f} + {Lin_model.coef_[0]:,.0f} \u00d7 years_experience")

Lin_model1 = LinearRegression() # Instantiate the model
Lin_model1.fit(df[['edu_norm']], df['salary_lpa']) # Pass X as a DataFrame and y as a Series
print(f"   Salary = {Lin_model1.intercept_:,.0f} + {Lin_model1.coef_[0]:,.0f} \u00d7 edu_norm")

   Salary = 9 + 1 × years_experience
   Salary = 9 + 16 × edu_norm

In [13]:
df.head(5)

   years_experience  education_level  certifications  salary_lpa  edu_norm
0              9.38                2               2       22.96  0.624246
1             13.46                1               2       23.48  0.897522
2             11.64                0               3       20.78  0.775620
3              3.38                2               3       14.55  0.222371
4              4.50                1               1       13.11  0.297388

create a model for polynominal regrssion.

In [15]:
df['YOE_degree_2'] = df['years_experience']**2

In [16]:
df['YOE_degree_3'] = df['years_experience']**3

In [17]:
df.head(5)

,years_experience,education_level,certifications,salary_lpa,edu_norm,YOE_degree_2,YOE_degree_3
0,9.38,2,2,22.96,0.624246,87.9844,825.293672
1,13.46,1,2,23.48,0.897522,181.1716,2438.569736
2,11.64,0,3,20.78,0.775620,135.4896,1577.098944
3,3.38,2,3,14.55,0.222371,11.4244,38.614472
4,4.50,1,1,13.11,0.297388,20.2500,91.125000

train_df  (400, 7)
test_df  (100, 7)

In [34]:
model_feature_cols = ['years_experience','education_level','certifications','edu_norm','YOE_degree_2','YOE_degree_3']
Scaler1 = MinMaxScaler()
normalized = Scaler1.fit_transform(df[model_feature_cols])
for index,feature in enumerate(model_feature_cols):
  df[feature + '_norm1'] = normalized[:,index]
df[[c + '_norm1' for c in model_feature_cols]].describe().loc[['min','max']]
df.drop(columns='edu_norm_norm1')

,years_experience,education_level,certifications,salary_lpa,edu_norm,YOE_degree_2,YOE_degree_3,years_experience_norm1,education_level_norm1,certifications_norm1,YOE_degree_2_norm1,YOE_degree_3_norm1
0,9.38,2,2,22.96,0.624246,87.9844,825.293672,0.624246,1.0,0.4,0.391554,0.245021
1,13.46,1,2,23.48,0.897522,181.1716,2438.569736,0.897522,0.5,0.4,0.806279,0.723986
2,11.64,0,3,20.78,0.775620,135.4896,1577.098944,0.775620,0.0,0.6,0.602973,0.468224
3,3.38,2,3,14.55,0.222371,11.4244,38.614472,0.222371,1.0,0.6,0.050828,0.011464
4,4.50,1,1,13.11,0.297388,20.2500,91.125000,0.297388,0.5,0.2,0.090106,0.027054
...,...,...,...,...,...,...,...,...,...,...,...,...
495,1.10,0,1,7.60,0.069658,1.2100,1.331000,0.069658,0.0,0.2,0.005369,0.000395
496,13.00,1,1,20.20,0.866711,169.0000,2197.000000,0.866711,0.5,0.2,0.752110,0.652267
497,4.69,2,5,16.37,0.310114,21.9961,103.161709,0.310114,1.0,1.0,0.097876,0.030628
498,7.42,1,2,18.22,0.492967,55.0564,408.518488,0.492967,0.5,0.4,0.245010,0.121285
499,2.97,0,1,10.81,0.194910,8.8209,26.198073,0.194910,0.0,0.2,0.039241,0.007778

In [32]:
train_df,test_df = train_test_split(df,test_size=0.2,random_state=1)
train_df =train_df.reset_index(drop=True)
test_df =test_df.reset_index(drop=True)
print('train_df ',train_df.shape)
print('test_df ',test_df.shape)

train_df  (400, 13)
test_df  (100, 13)

In [52]:
model_a_feature = ['years_experience_norm1','education_level_norm1','certifications_norm1']
model_a = LinearRegression()
model_a.fit(train_df[model_a_feature],train_df['salary_lpa'])
for feature,coef in zip(model_a_feature,model_a.coef_):
  print(f"{feature:<}  is {coef:>}")
print(f"Intercept  is {model_a.intercept_}")
model_a_predict = model_a.predict(test_df[model_a_feature])
print(f" r2 value is {r2_score(test_df['salary_lpa'], model_a_predict):.2f}")
print("Predicted:", model_a_predict[:10])
print("Actual:", test_df['salary_lpa'].values[:10])

years_experience_norm1  is 15.814713837443977
education_level_norm1  is 3.0222370595703505
certifications_norm1  is 1.3613900178583744
Intercept  is 7.086673100425051
 r2 value is 0.92
Predicted: [22.59563241 14.88472882 18.22451875 12.94266804 10.20835366 18.24208427
 16.46230737 13.55319336 16.57471535  8.17145041]
Actual: [23.88 15.14 20.74 10.37 10.86 18.68 17.19 15.19 16.69  5.13]

In [57]:
model_b_feature = ['years_experience_norm1','education_level_norm1','certifications_norm1','YOE_degree_2_norm1']
model_b = LinearRegression()
model_b.fit(train_df[model_b_feature],train_df['salary_lpa'])
for feature,coef in zip(model_b_feature,model_b.coef_):
  print(f"{feature:<} is {coef:>}")
print(f"Intercept is {model_b.intercept_}")
model_b_predict = model_b.predict(test_df[model_b_feature])
print(f"r2 value is {r2_score(test_df['salary_lpa'],model_b_predict)}")
print(model_b_predict[:10])

years_experience_norm1 is 32.812753679229004
education_level_norm1 is 3.0598571345554255
certifications_norm1 is 1.4023806777782195
YOE_degree_2_norm1 is -16.985201085979742
Intercept is 4.215696590515943
r2 value is 0.9563739854639637
[23.19606259 15.6909884  19.5977572  11.57417961  9.83679214 19.60947169
 17.80672553 13.84922159 17.70925268  5.87322556]

In [47]:
model_c_feature = ['years_experience_norm1','education_level_norm1','certifications_norm1','YOE_degree_2_norm1','YOE_degree_3_norm1']
model_c = LinearRegression()
model_c.fit(train_df[model_c_feature],train_df['salary_lpa'])
for feature,coef in zip(model_c_feature,model_c.coef_):
  print(f"{feature:<} is {coef:>}")
print(f"Intercept is {model_c.intercept_}")

years_experience_norm1 is 32.52264891213451
education_level_norm1 is 3.061904177598535
certifications_norm1 is 1.4026821083480914
YOE_degree_2_norm1 is -16.264717239121236
YOE_degree_3_norm1 is -0.4782107850599884
Intercept is 4.238153592861298